# -*- coding: utf-8 -*-
"""introduction_to_sets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dLvXEiFz5B8mJBA7nIvob8GGtoQ4YbZD
"""

def average(array):
    return sum(set(arr)) / len(set(arr))


if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

