# -*- coding: utf-8 -*-
"""StringValidators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ukhwImftHItcc4e8NWlpDmMnxvDp44KV

Task

You are given a string S.
Your task is to find out if the string S contains: alphanumeric characters, alphabetical characters, digits, lowercase and uppercase characters.

The any() function returns a boolean value:
- True if at least one element of an iterable is true
- False if all elements are false or if an iterable is empty
"""

s = input()
print(any(c.isalnum() for c in s))
print(any(c.isalpha() for c in s))
print(any(c.isdigit() for c in s))
print(any(c.islower() for c in s))
print(any(c.isupper() for c in s))