# -*- coding: utf-8 -*-
"""Set .intersection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjW8IkvX1Xq2A3qqmhC_ZxCgEpfltQVD
"""

a = input()
a1 = set(input().split())

b = input()
b1 = set(input().split())

print(len(a1.intersection(b1)))